grond go CONFIG/flegrei.devi.XL.final.gronf all --parallel=8 --force
grond report runs/cmt_devi_XL_final_flegrei* --parallel=8
grond go CONFIG/flegrei.devi.L.final.gronf all --parallel=8 --force
grond report runs/cmt_devi_L_final_flegrei* --parallel=8
grond go CONFIG/flegrei.devi.M.final.gronf all --parallel=8 --force
grond report runs/cmt_devi_M_final_flegrei* --parallel=8
grond go CONFIG/flegrei.devi.S.final.gronf all --parallel=8 --force
grond report runs/cmt_devi_S_final_flegrei* --parallel=8